on:
    push:
        branches:
            - main
    workflow_dispatch:
    workflow_call:
    pull_request:

jobs:
    ubuntu:
        name: Continuous Integration
        uses: ./.github/workflows/ci-single-platform.yaml
        with:
            name: Ubuntu
            platform: ubuntu-latest
    macos:
        name: Continuous Integration
        uses: ./.github/workflows/ci-single-platform.yaml
        with:
            name: MacOS
            platform: macos-latest
    win:
        name: Continuous Integration
        uses: ./.github/workflows/ci-single-platform.yaml
        with:
            name: Windows
            platform: windows-latest
