name: Release
on:
    release:
        types: [created]
    workflow_call:
jobs:
    ci:
        uses: ./.github/workflows/ci.yaml
        permissions:
            contents: read
            id-token: write
    release:
        runs-on: ubuntu-latest
        needs: ci
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup npm authenication
              uses: actions/setup-node@v3
              with:
                  registry-url: https://registry.npmjs.org/

            - name: Install dependencies
              run: npm install

            - name: Build
              run: npm run build

            - name: Publish
              run: npm publish --access=public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.npm_token}}
    docs:
        runs-on: ubuntu-latest
        name: Docs build and deploy
        permissions:
            contents: write
            id-token: write
            pages: write
        environment:
            name: github-pages
            url: ${{ steps.deploy.outputs.page_url }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install dependencies
              run: npm install

            - name: Build docs
              run: npm run build:docs

            - name: Upload docs artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: ./docs

            - name: 'Deploy docs'
              id: deploy
              uses: actions/deploy-pages@v4
